Fitness_Counter/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

urlpatterns += [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'counter/', include('counter.urls', namespace='counter')),
]

urlpatterns += staticfiles_urlpatterns()

counter/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^$', views.WorkoutListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', views.WorkoutDetailView.as_view(), name='detail'),
    url(r'^create/$', views.WorkoutCreateView.as_view(), name='create'),
    url(r'^edit/(?P<pk>\d+)/$', views.WorkoutUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', views.WorkoutDeleteView.as_view(), name='delete'),
    url(r'exercise/$', views.ExerciseCreateView.as_view(), name='exercise_create'),
    url(r'exercise/(?P<pk>\d+)/$', views.ExerciseDetailView.as_view(), name='exercise_detail'),
    url(r'^exercise/edit/(?P<pk>\d+)/$', views.ExerciseUpdateView.as_view(), name='exercise_update'),
    url(r'^exercise/delete/(?P<pk>\d+)/$', views.ExerciseDeleteView.as_view(), name='exercise_delete'),
]

counter/models.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models

# Create your models here.
class Workout(models.Model):
    # need title, description, maybe created_at
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('counter:detail', kwargs={'pk': self.pk})


class Exercise(models.Model):
    # need title muscle group, equipment used, sets, reps, weight, workout foreign key
    title = models.CharField(max_length=255)
    MUSCULE_GROUP_CHOICES = (
        ('ch', 'Chest'),
        ('ar', 'Arms'),
        ('le', 'Legs'),
        ('ba', 'Back'),
        ('co', 'Core'),
    )
    muscule_group = models.CharField(
        max_length=2,
        choices=MUSCULE_GROUP_CHOICES,
    )
    EQUIPMENT_USED = (
        ('db', 'Dumbbell'),
        ('bb', 'Barbell'),
        ('bw', 'Body Weight'),
        ('rb', 'Resistance Bands'),
        ('ma', 'Machine'),
    )
    equipment = models.CharField(
        max_length=2,
        choices=EQUIPMENT_USED,
    )
    description = models.TextField(blank=True, default='')
    workout = models.ForeignKey(Workout, related_name='exercises')
    sets = models.IntegerField(default=1)
    reps = models.IntegerField(default=1)
    weight = models.IntegerField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('counter:exercise_detail', kwargs={'pk': self.pk})

Fitness_Counter/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView


class HomeView(TemplateView):
    template_name = 'home.html'

counter/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, get_object_or_404
from django.views.generic import (
    ListView, DetailView,
    CreateView, UpdateView, DeleteView
)

from . import mixins
from . import models

############# WORKOUT VIEWS #################
class WorkoutListView(CreateView, ListView):
    context_object_name = 'workouts'
    model = models.Workout
    fields = ('title', 'description')
    template_name = 'counter/workout_list.html'



class WorkoutDetailView(DetailView, UpdateView):
    fields = ('title', 'description')
    model = models.Workout
    template_name = 'counter/workout_detail.html'


class WorkoutCreateView(CreateView):
    fields = ('title', 'description')
    model = models.Workout
    template_name = 'counter/workout_create.html'


class WorkoutUpdateView(UpdateView):
    fields = ('title', 'description')
    model = models.Workout

    def get_page_title(self):
        obj = self.get_object()
        return "Update {}".format(obj.name)


class WorkoutDeleteView(DeleteView):
    model = models.Workout
    success_url = reverse_lazy('counter:list')


############ Exercise views ##############
class ExerciseCreateView(CreateView):
    fields = ('title', 'muscule_group', 'equipment', 'sets', 'reps', 'weight', 'workout')
    model = models.Exercise
    template_name = 'counter/exercise_create.html'
    success_url = reverse_lazy('counter:list')


class ExerciseDetailView(DetailView):
    context_object_name = 'exercise'
    # fields = ('title', 'equipment')
    model = models.Exercise
    template_name = 'counter/exercise_detail.html'


class ExerciseUpdateView(UpdateView):
    fields = ('title', 'muscule_group', 'equipment', 'sets', 'reps', 'weight', 'workout')
    model = models.Exercise


class ExerciseDeleteView(DeleteView):
    model = models.Exercise
    success_url = reverse_lazy('counter:list')

counter/templates/counter/_layout.html
{% extends "layout.html" %}

{% block side-bar %}
<div class="side-bar">  
</div>
{% endblock side-bar %}

counter/templates/counter/exercise_confirm_delete.html
{% extends "counter/_layout.html" %}

{% block content %}
<div class="delete-view">
    <h1>Delete {{ exercise.title }}?</h1>

    <form method="POST">
        {% csrf_token %}
        <input type="submit" class="btn-danger" value="Delete"> 
        <br>
        <a href="{% url 'counter:exercise_detail' pk=exercise.pk %}" class="btn-cancel">Cancel</a>
    </form>
</div>
{% endblock content %}

counter/templates/counter/exercise_create.html
{% extends "counter/_layout.html" %}

{% block content %}
<div class="create-exercise">
    <h1>Create a New Exercise</h1>

    <div class="current-workout">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="" value="Save">
            <a href="{% url 'counter:list' %}" class="">Cancel</a>
        </form>
    </div>
</div>

{% endblock content %}

counter/templates/counter/exercise_detail.html
{% extends "counter/_layout.html" %}

{% block content %}

<div class="exercise-detail">
    <h1>{{ exercise }}</h1>
    <h3>{{ exercise.get_muscule_group_display }} | {{ exercise.get_equipment_display }}</h3>
    <p>{{ exercise.description }}</p>
    <hr>
    <h4>{{ exercise.sets }} sets | {{ exercise.reps }} reps</h4>
    <h4>Weight: {{ exercise.weight }} lbs</h4>
    
    <div class="buttons">
        <a href="{% url 'counter:exercise_update' pk=exercise.pk %}" class="btn edit">Edit</a>
        <a href="{% url 'counter:exercise_delete' pk=exercise.pk %}" class="btn delete">Delete</a>
        <a href="{% url 'counter:list' %}" class="btn return">Save</a>
    </div>

</div>

{% endblock %}

counter/templates/counter/exercise_form.html
{% extends "layout.html" %}

{% block content %}

<div class="side-bar">
    <h2>Side-bar/Saved Workouts</h2>
    <p>future workout links</p>    
</div>

<div class="edit-exercise">
    <h1>{{ page_title }}</h1>
    
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="" value="Save">
            <a href="{% url 'counter:list' %}" class="">Cancel</a>
        </form>
</div>


{% endblock %}

counter/templates/counter/workout_confirm_delete.html
{% extends "counter/_layout.html" %}

{% block content %}
<div class="delete-view">
    <h1>Delete {{ workout.title }}?</h1>

    <form method="POST">
        {% csrf_token %}
        <input type="submit" class="btn-danger" value="Delete"> 
        <br>
        <a href="{% url 'counter:detail' pk=workout.pk %}" class="btn-cancel">Cancel</a>
    </form>
</div>
{% endblock content %}

counter/templates/counter/workout_create.html
{% extends "counter/_layout.html" %}

{% block content %}


    <div class="create-workout">
        <h1>Create a new Workout</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="" value="Save">
            <a href="{% url 'counter:list' %}" class="">Cancel</a>
        </form>

    </div>
{% endblock %}

counter/templates/counter/workout_detail.html
{% extends "counter/_layout.html" %}

{% block content %}

<div class="workout-detail">
    <h1>{{ workout }}</h1>
    <h4>{{ workout.description }}</h4>

    <div class="exercises">
        {% for exercise in workout.exercises.all %}
        <a href="{% url 'counter:exercise_detail' pk=exercise.pk %}"><div class="exercise">
            <h2>{{ exercise.title }}</h2>
            <h3>{{ exercise.get_equipment_display }} Exercise</h3>
            <h3>{{ exercise.get_muscule_group_display }}</h3>
            <p>Number of sets: {{ exercise.sets }}</p>
            <p>Reps per set: {{ exercise.reps }}</p>
            {% if exercise.weight is not 0 %}
            <p>Weight: {{ exercise.weight }} lbs.</p>
            {% endif %}
            
        </div>
        </a>
        {% endfor %}
    </div>

    <div class="add-exercises">
        <a href="{% url 'counter:exercise_create' %}" class="btn add">Add Exercise</a>
    </div>

    <div class="buttons">
        <a href="{% url 'counter:update' pk=workout.pk %}" class="btn edit">Edit</a>
        <a href="{% url 'counter:delete' pk=workout.pk %}" class="btn delete">Delete</a>
        <a href="{% url 'counter:list'  %}" class="btn return">Return to List</a>
    </div>

</div>




{% endblock content %}

counter/templates/counter/workout_form.html
{% extends "counter/_layout.html" %}

{% block content %}


<div class="edit-workout">
    <h1>Edit</h1>
    
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="" value="Save">
        <a href="{% url 'counter:detail' pk=workout.pk %}" class="">Cancel</a>
    </form>

    <div class="exercise-edit-list">
        {% for exercise in workout.exercises.all %}
        <a href="{% url 'counter:exercise_update' pk=exercise.pk %}"><h3>{{exercise.title}} | sets: {{exercise.sets}} | reps: {{exercise.reps}}</h3></a>
        {% endfor %}
    </div>

</div>
{% endblock %}

counter/templates/counter/workout_list.html
{% extends "counter/_layout.html" %}

{% block content %}

<div class="current-workout">
    <div class="current-workout-block">
        <h1>Current Workouts:</h1>
        <ul>
        {% for workout in workouts  %}
            <li>
                <a href="{% url 'counter:detail' pk=workout.pk %}">
                    <h3>{{ workout.title }}</h3>
                    <p>{{ workout.description }}</p>
                    <p>{{ workout.pk }}</p>
                </a>
            </li>
        {% endfor %}    
        </ul>  
    </div>

    <div class="create-workout-list">
        <h1>Create a New Workout:</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="" value="Save">
        </form>
    </div>
</div>

{% endblock content %}

templates/home.html
{% extends 'layout.html' %}

{% block title %} Lift Log{% endblock %}

{% block content %}
<div class="home">
    <h1>Lift Log</h1>
    <p>Create and manage a workout routine.</p>
</div>

<div class="space">
        <a href="{% url 'counter:create' %}">Create a new workout</a>
        <a href="{% url 'counter:exercise_create' %}">Create a new exercise</a>
</div>

{% endblock %}

templates/layout.html
<!doctype html>
{% load static from staticfiles %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="body">
    <div class="hero">
        <h1>Lift Log</h1>

        <div class="nav-button">
            <div class="hamburger"></div>
        </div>

        <div class="nav">
            <ul>
                <li>
                    <a href="{% url 'home' %}">Home</a>
                </li>
                <li>
                    <a href="{% url 'counter:list' %}">See a list of current workouts</a>
                </li>
                <li>
                    <a href="{% url 'counter:create' %}">Create a new workout</a>
                </li>
                <li>
                    <a href="{% url 'counter:exercise_create' %}">Create a new exercise</a>
                </li>
            </ul>
        </div>
    </div>

    {% block side-bar %}{% endblock %}

    {% block content %}{% endblock %}

    <div class="footer">
        <a href="{% url 'home' %}">home</a>
        <p>© Jeff Thomas 2017</p>
    </div>
</div>


<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script>
    var $navButton = $('.nav-button')
    
    
    $('.nav').hide();
    
    $navButton.click(function() {
        $navButton.toggleClass('nav-button-transform')
        $('.nav').slideToggle();
    })
    
    $('.nav').children().click(function() {
        $(this).parent().hide();
        $navButton.removeClass('nav-button-transform');
    })
</script>
</body>

</html>